spring:
  application:
    name: antijob

  datasource:
    url: jdbc:postgresql://localhost:5432/dental_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

jwt:
  secret: dGhpcy1pcy1hLWRldi1vbmx5LXNlY3JldC1rZXktY2hhbmdlLWluLXByb2Q= # base64, đổi khi lên prod
  expiration-ms: 86400000 # 24h
